---
name: Upload Test Result

on:
  push:
    branches: [main]
    paths:
      - 'test/**'
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm test -- -u --test-timeout=30000 --reporter=json --outputFile=./result.json
      - run: pnpm upload
        if: always()
        env:
          NEXT_PUBLIC_SANITY_DATASET: ${{secrets.NEXT_PUBLIC_SANITY_DATASET}}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{secrets.NEXT_PUBLIC_SANITY_PROJECT_ID}}
          SANITY_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
          
