---
name: Upload Test Result

on:
  push:
    branches: [main]
    paths:
      - 'test/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
      - run: pnpm install
      - run: pnpm test -- --max-concurrency=2 --test-timeout=30000 --reporter=json --outputFile=./result.json
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: test/result.json
          if-no-files-found: error
      - run: pnpm upload
        if: always()
        env:
          NEXT_PUBLIC_SANITY_DATASET: ${{secrets.NEXT_PUBLIC_SANITY_DATASET}}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{secrets.NEXT_PUBLIC_SANITY_PROJECT_ID}}
          SANITY_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
          
